# Generated by Django 3.0.2 on 2020-01-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=120)),
                ('lname', models.CharField(max_length=120, null=True)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('acc_type', models.TextField()),
            ],
        ),
    ]
